language: php
php:
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini || return 0 # Turn off XDebug

script:
  - composer validate
  - composer qa

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done # Print *.actual content

jobs:
  include:
    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.4
      script:
        - composer outdated --direct

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files
